# [[redirects]]
#   from = "/db.json"
#   to = "/days"
#   status = 301
#   force = false

[[redirects]]
  from = "/db.json"
  to = "/days"
  status = 200
  force = true # COMMENT: ensure that we always redirect